version: "3"

services:
  mysqldb:
    image: mysql:8.0-oracle # MySQL8.0イメージを使用
    container_name: mysql8_container
    environment:
      MYSQL_ROOT_PASSWORD: root # rootのパスワード
      MYSQL_DATABASE: test_database # テストデータベースの名前
      MYSQL_USER: torichan # 一般ユーザーの名前
      MYSQL_PASSWORD: torichan1234 # 一般ユーザーのパスワード
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306" # MySQLのポート番号を指定
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysqldb
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS='mysqldb'
    ports:
      - "3000:80" # phpMyAdminのポート番号を指定
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
